#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.3'
__CHEETAH_versionTuple__ = (2, 4, 3, 'development', 0)
__CHEETAH_genTime__ = 1284932136.2291241
__CHEETAH_genTimestamp__ = 'Sun Sep 19 23:35:36 2010'
__CHEETAH_src__ = 'browse.tmpl'
__CHEETAH_srcLastModified__ = 'Sun Sep 19 23:31:25 2010'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class browse(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(browse, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>ES</title>
<!-- META -->
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<!-- CSS -->
<link rel="stylesheet" type="text/css" href="horizon.css" />
<!-- SCRIPTS -->
</head>
<body>
<div id="header">
<div class="inside">
<h1><a href="index.html" title="Return to current image">ES</a></h1>
<ul>
<li><a href="index.html" title="Return to Homepage">Home</a></li>
<li><a href="browse.html" title="Browse">Browse</a></li>
<li><a href="about.html" title="About">About</a></li>
</ul>
</div> <!-- /inside -->
</div> <!-- /header -->

<div id="infobox">
<div id="page">
<h2>Browse Archive:</h2>
<div id="thumbnails">
<br /><br />
''')
        for photo in VFFSL(SL,"photos",True): # generated from line 28, col 1
            write(u'''<a href="''')
            _v = VFFSL(SL,"photo.week",True) # u'${photo.week}' on line 29, col 10
            if _v is not None: write(_filter(_v, rawExpr=u'${photo.week}')) # from line 29, col 10.
            write(u'''.html"><img src="''')
            _v = VFFSL(SL,"photo.small_url",True) # u'${photo.small_url}' on line 29, col 40
            if _v is not None: write(_filter(_v, rawExpr=u'${photo.small_url}')) # from line 29, col 40.
            write(u''' " alt="''')
            _v = VFFSL(SL,"photo.week",True) # u'${photo.week}' on line 29, col 66
            if _v is not None: write(_filter(_v, rawExpr=u'${photo.week}')) # from line 29, col 66.
            write(u'''" title="''')
            _v = VFFSL(SL,"photo.week",True) # u'${photo.week}' on line 29, col 88
            if _v is not None: write(_filter(_v, rawExpr=u'${photo.week}')) # from line 29, col 88.
            write(u'''"  class="thumbnails" /></a>
''')
        write(u'''</div> <!--/thumbnails -->
</div> <!--/page-->
</div> <!--/infobox-->

<div id="footer">
<ul>
<li>Designed by <a href="http://www.cancerbox.com" title="Designed by Scott Craig">SCraig</a></li>
<li>This website uses valid <a href="http://validator.w3.org/check/referer" title="This website uses Valid xHTML">xHTML</a> / <a href="http://jigsaw.w3.org/css-validator/check/referer" title="This website uses Valid CSS2">CSS</a></li>
</ul>
<ul>
<li>&copy; ES</li>
<li><a href=\'./index.php?x=rss\'>RSS 2.0</a></li>
<li><a href=\'./index.php?x=atom\'>ATOM feed</a></li>
<li><a href="admin/index.php">Login</a></li>
</ul>
</div>


</body>
</html>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_browse= 'respond'

## END CLASS DEFINITION

if not hasattr(browse, '_initCheetahAttributes'):
    templateAPIClass = getattr(browse, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(browse)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=browse()).run()


