#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.3'
__CHEETAH_versionTuple__ = (2, 4, 3, 'development', 0)
__CHEETAH_genTime__ = 1284932629.0467291
__CHEETAH_genTimestamp__ = 'Sun Sep 19 23:43:49 2010'
__CHEETAH_src__ = 'image_page.tmpl'
__CHEETAH_srcLastModified__ = 'Sun Sep 19 23:43:36 2010'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class image_page(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(image_page, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>ES</title>
<!-- Link for ATOM feed autodiscovery -->
<link rel="service.feed" type="application/x.atom+xml" title="ES - ATOM Feed" href="http://messze.net/es/atom.xml" />
<!-- META -->
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta http-equiv="content-type" name="keywords" content="ES" />
<meta http-equiv="content-type" name="description" content="ES-PhotoBlog: 25, " />
<!-- CSS -->
<link rel="stylesheet" type="text/css" href="horizon.css" />
<!-- SCRIPTS -->
</head>

<body>

<div id="image-info" style="display:none">

<div class="inside">
<h2>''')
        _v = VFFSL(SL,"photo.week",True) # u'${photo.week}' on line 21, col 5
        if _v is not None: write(_filter(_v, rawExpr=u'${photo.week}')) # from line 21, col 5.
        write(u''' <em>''')
        _v = VFFSL(SL,"photo.imagetime",True) # u'${photo.imagetime}' on line 21, col 23
        if _v is not None: write(_filter(_v, rawExpr=u'${photo.imagetime}')) # from line 21, col 23.
        write(u'''</em> </h2>

<div id="image_comments">
<ul><li>No Comments Yet.</li></ul>
</div> <!--/image comments -->

</div>  <!-- /inside -->
<div class="clear"></div>
</div> <!--/d2 -->

<div id="header">
<div class="inside">
<h1><a href="index.php" title="Return to current image">ES</a></h1>
<ul>
<li><a href="index.html" title="Return to Homepage">Home</a></li>
<li><a href="browse.html" title="Browse">Browse</a></li>
</ul>
</div> <!-- /inside -->
</div> <!-- /header -->

<div id="photobox">
''')
        if (VFFSL(SL,"photo.week",True) > 1): # generated from line 42, col 1
            write(u'''<a href="''')
            _v = VFFSL(SL,"photo.week",True)-1 # u'${photo.week-1}' on line 43, col 10
            if _v is not None: write(_filter(_v, rawExpr=u'${photo.week-1}')) # from line 43, col 10.
            write(u'''.html">
''')
        write(u'''<img src="''')
        _v = VFFSL(SL,"photo.normal_url",True) # u'${photo.normal_url}' on line 45, col 11
        if _v is not None: write(_filter(_v, rawExpr=u'${photo.normal_url}')) # from line 45, col 11.
        write(u'''" alt="''')
        _v = VFFSL(SL,"photo.week",True) # u'${photo.week}' on line 45, col 37
        if _v is not None: write(_filter(_v, rawExpr=u'${photo.week}')) # from line 45, col 37.
        write(u'''" title="''')
        _v = VFFSL(SL,"photo.week",True) # u'${photo.week}' on line 45, col 59
        if _v is not None: write(_filter(_v, rawExpr=u'${photo.week}')) # from line 45, col 59.
        write(u'''" width="''')
        _v = VFFSL(SL,"photo.width",True) # u'${photo.width}' on line 45, col 81
        if _v is not None: write(_filter(_v, rawExpr=u'${photo.width}')) # from line 45, col 81.
        write(u'''" height="''')
        _v = VFFSL(SL,"photo.height",True) # u'${photo.height}' on line 45, col 105
        if _v is not None: write(_filter(_v, rawExpr=u'${photo.height}')) # from line 45, col 105.
        write(u'''" id="photo" />
''')
        if (VFFSL(SL,"photo.week",True) > 1): # generated from line 46, col 1
            write(u'''</a>
''')
        write(u'''</div> <!-- /photo -->

<div id="infobox">
<div id="image-navigate" class="inside">
<ul>

<li class="left">
''')
        if (VFFSL(SL,"photo.week",True) > 1): # generated from line 56, col 1
            write(u"""<a href='""")
            _v = VFFSL(SL,"photo.week",True)-1 # u'${photo.week-1}' on line 57, col 10
            if _v is not None: write(_filter(_v, rawExpr=u'${photo.week-1}')) # from line 57, col 10.
            write(u""".html'>
Previous
</a>
""")
        write(u'''</li>

<li class="left" style="text-align:center">''')
        _v = VFFSL(SL,"photo.imagetime",True) # u'${photo.imagetime}' on line 63, col 44
        if _v is not None: write(_filter(_v, rawExpr=u'${photo.imagetime}')) # from line 63, col 44.
        write(u'''</li>
<li class="right" style="text-align:right">
''')
        if (VFFSL(SL,"photo.week",True) < VFFSL(SL,"currentweek",True)): # generated from line 65, col 1
            write(u"""<a href='""")
            _v = VFFSL(SL,"photo.week",True)+1 # u'${photo.week+1}' on line 66, col 10
            if _v is not None: write(_filter(_v, rawExpr=u'${photo.week+1}')) # from line 66, col 10.
            write(u""".html'>
Next
</a>
""")
        write(u'''
</li>
</ul>
</div>
</div> <!--/infobox -->


<div id="footer">
<ul>
<li>Designed by <a href="http://www.cancerbox.com" title="Designed by Scott Craig">SCraig</a></li>
<li>This website uses valid <a href="http://validator.w3.org/check/referer" title="This website uses Valid xHTML">xHTML</a> / <a href="http://jigsaw.w3.org/css-validator/check/referer" title="This website uses Valid CSS2">CSS</a></li>
</ul>
<ul>
<li>&copy; ES</li>
<li><a href=\'atom.xml\'>ATOM feed</a></li>
</ul>
</div>


</body>
</html>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_image_page= 'respond'

## END CLASS DEFINITION

if not hasattr(image_page, '_initCheetahAttributes'):
    templateAPIClass = getattr(image_page, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(image_page)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=image_page()).run()


